import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomeSwiper from "../components/HomeSwiper";
import { useEffect, useState } from "react";
import BreakfastMenu from "../components/BreakfastMenu";
import LunchMenu from "../components/LunchMenu";
import DinnerMenu from "../components/DinnerMenu";
import { getAllSubscriptions, getCartItems } from "../services/apiServices";
import { toast } from "react-toastify";

export const Home = ({setCartCount}) => {
  const [activeTab, setActiveTab] = useState("breakfast");

  const [foodData, setFoodData] = useState();

  useEffect(() => {
    mealData();
  }, [activeTab]);

  const mealData = () => {
    getAllSubscriptions(activeTab)
      .then((res) => {
        if (res?.status) {
          setFoodData(res?.data);
        }
      })
      .catch((err) => toast.error(err));
  };

  // useEffect(()=> {
  //   getCartItems().then((res)=> {
  //     if(res?.status === 200) {
  //       setCartCount(res?.data?.length)
  //     }
  //   }).catch((err)=> toast.error(err));
  // },[]) 

  return (
    <>
      <Head>
        <title>Book your Tiffin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home_page}>
        <HomeSwiper />
        <div className={styles.page_header}>
          <h1 className={styles.page_heading}>Meal Plans</h1>
          <div className={styles.tabs}>
            <div
              className={`${styles.tab_element} ${
                activeTab === "breakfast" && styles.active_tab
              }`}
              onClick={() => {
                setActiveTab("breakfast");
              }}
            >
              Breakfast
            </div>
            <div
              className={`${styles.tab_element} ${
                activeTab === "lunch" && styles.active_tab
              }`}
              onClick={() => {
                setActiveTab("lunch");
              }}
            >
              Lunch
            </div>
            <div
              className={`${styles.tab_element} ${
                activeTab === "dinner" && styles.active_tab
              }`}
              onClick={() => {
                setActiveTab("dinner");
              }}
            >
              Dinner
            </div>
          </div>
        </div>

        <div>
          {activeTab === "breakfast" ? (
            <BreakfastMenu data={foodData} />
          ) : activeTab === "lunch" ? (
            <LunchMenu data={foodData} />
          ) : (
            <DinnerMenu data={foodData} />
          )}
        </div>
      </div>
    </>
  );
};

export default Home;
